const catchError = require("../utils/catch-error");

exports.searchTrack = catchError(async (req, res, next) => {});
